config/routes.rb
Cribber::Application.routes.draw do

  root to: 'sessions#home'
  match '/create_session/:user_id' => 'sessions#create', as: :create_session

  match '/logout' => 'sessions#destroy',    as: :logout

  resources :users
  match '/get_in' => 'users#new',  as: :get_in

  match '/admin_credentials' => 'tweeters#admin_credentials',  as: :admin_credentials
  match '/save_admin_credentials' => 'tweeters#save_admin_credentials',  as: :save_admin_credentials
  match "/tweeters/authentication" => 'tweeters#authentication',                   as: :authentication
  match '/twitter_credentials' => 'tweeters#twitter_credentials',     as: :twitter_credentials
  match '/destroy_all_tweets' => 'tweets#destroy_all_tweets',         as: :destroy_all_tweets

  match "/tweets" => 'tweets#tweets',                                 as: :tweets
  match '/retweet_this/:id' => 'tweets#retweet',                          as: :retweet
  match '/delete_tweet/:id' => 'tweets#destroy',                           as: :delete_tweet
  match '/post_tweet' => 'tweets#post_tweet',                           as: :post_tweet

  match '/purge_images' => 'images#purge',                  as: :purge_images
end

app/models/image.rb
class Image < ActiveRecord::Base
  has_attached_file :tweet_img, styles: {tiny: '35x35>'}

  def self.save_tweet_images(tweet)
    if tweet['retweeted_status']
      user = tweet['retweeted_status']['user']
    else
      user = tweet['user']
    end
    unless Image.find_by_twitter_id(user['id_str'])
      image = Image.new(twitter_id: user['id_str'], tweet_img: open(user['profile_image_url']), screen_name: user['screen_name'])
      image.save!
    end
  end
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :user
  has_attached_file :user_img, styles: {tiny: '35x35>'}
        
  def store(tweet)
    if tweet['retweeted_status']
      self.user_name = tweet['retweeted_status']['user']['name']
      self.user_screen_name = tweet['retweeted_status']['user']['screen_name']
      self.twitter_id = tweet['retweeted_status']['user']['id_str']
      self.retweeter_name = tweet['user']['name']
      self.retweeter_screen_name = tweet['user']['screen_name']

    else
      self.user_name = tweet['user']['name']
      self.user_screen_name = tweet['user']['screen_name']
      self.twitter_id = tweet['user']['id_str']
    end

    self.tweet_id = tweet['id_str']
    self.text = tweet['text']
    self.created_at = tweet['created_at']
  end

  def is_retweeted?
    self.retweeter_name?
  end

end

app/models/tweeter.rb
class Tweeter < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_one :tweeter, dependent: :destroy
  has_many :tweets, dependent: :destroy
  attr_accessor :password

  validates :name, uniqueness: {case_sensitive: false}, presence: true
  before_save :encrypt_new_password
  before_save :first_user_is_admin
  after_create :spawn_tweeter

  def confirm_password?(string)
    crypted_password == encrypt(string)
  end

private
  def first_user_is_admin
    self.is_admin = true unless User.find_by_is_admin(true)
  end

  def password_present?
    password.present? 
  end

  def encrypt_new_password
    return if password.blank?
    self.salt = SecureRandom.base64(8)
    self.crypted_password = encrypt(password)
  end

  def encrypt(string)
    Digest::SHA2.hexdigest(string + self.salt)
  end

  def spawn_tweeter
    self.create_tweeter!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :check_login
  helper_method :current_user, :admin

private
  def current_user
    return nil unless session[:user_id]
    raise ActiveRecord::RecordNotFound unless User.find(session[:user_id])
    @current_user ||= User.find(session[:user_id])
  end

  def get_client
    @client ||= TwitterOAuth::Client.new(consumer_key: admin.tweeter.consumer_key, consumer_secret: admin.tweeter.consumer_secret)
  end

  def admin
    @admin ||= User.find_by_is_admin(true)
  end

  def check_admin
    redirect_to tweets_path unless current_user.is_admin?
  end

  def check_login
    redirect_to root_path unless current_user
  end

  def confirm_twitter_credentials
    unless current_user.tweeter.token?
      redirect_to twitter_credentials_path
    end
  end

  def get_client
    @client = TwitterOAuth::Client.new(
      :consumer_key => admin.tweeter.consumer_key,
      :consumer_secret => admin.tweeter.consumer_secret,
      :token => current_user.tweeter.token, 
      :secret => current_user.tweeter.secret
    )
  end

end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_filter :get_client, only: [:purge]

  def purge
    Image.all.each do |image|
      if Tweet.find_by_user_screen_name(image.screen_name)
        user = @client.show(image.screen_name)
        image.update_attributes! tweet_img: open(user['profile_image_url'])
      else
        image.destroy
      end
    end
    redirect_to tweets_path
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_filter :check_login, only: [:create, :home]

  def create
    session[:user_id] = params[:user_id]
    if current_user.is_admin?
      redirect_to admin_credentials_path
    else
      redirect_to tweets_path
    end
  end

  def home
    if current_user.try(:is_admin?)
      redirect_to admin_credentials_path
    elsif current_user
      redirect_to tweets_path
    else
      redirect_to get_in_path
    end
  end

  def destroy
    reset_session
    redirect_to root_path
  end
end

app/controllers/tweeters_controller.rb
class TweetersController < ApplicationController
  before_filter :get_client, only: :authentication
  before_filter :check_admin, only: [:admin_credentials, :save_admin_credentials]

  def admin_credentials
    @tweeter = current_user.tweeter
  end

  def save_admin_credentials
    current_user.tweeter.update_attributes! params[:tweeter]
    redirect_to logout_path
  end

  def authentication
    access_token = @client.authorize(
      session[:r_token].token,
      session[:r_token].secret,
      :oauth_verifier => params[:oauth_verifier]
    )
    current_user.tweeter.update_attributes! token: access_token.token, secret: access_token.secret
    redirect_to tweets_path
  end

  def twitter_credentials
    request_token = get_client.request_token(oauth_callback: authentication_url)
    session[:r_token] = request_token
    redirect_to request_token.authorize_url
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  include TweetConfig

  before_filter :confirm_twitter_credentials, only: [:tweets]
  before_filter :get_client, only: [:tweets, :retweet, :post_tweet]
  before_filter :load_tweet, only: [:destroy]

  def tweets
    @client.home_timeline(count: TweetConfig.count).each do |timeline|
      next if Tweet.find_by_tweet_id(timeline['id_str'])
      Image.save_tweet_images(timeline)
      tweet = current_user.tweets.new
      tweet.store(timeline)
      tweet.save
    end
  end

  def destroy_all_tweets
    current_user.tweets.each{|tweet| tweet.destroy }
    redirect_to tweets_path
  end

  def retweet
    @client.retweet(params[:id])
    render nothing: true
  end

  def destroy
    
  end

  def post_tweet
    @client.update(params[:send_tweet])
    redirect_to tweets_path
  end

#######
private

  def load_tweet
    @tweet = Tweet.find(params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  skip_before_filter :check_login, only: [:new, :create]
  before_filter :confirm_twitter_credentials, only: [:edit]

  def show
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    registered_user = User.find(:first, conditions: ["lower(name) = ?", params[:user][:name].downcase])
    if registered_user.nil? and (@user = User.create(params[:user]))
      redirect_to create_session_path(@user.id)
    elsif registered_user.confirm_password?(params[:user][:password])
      redirect_to create_session_path(registered_user.id)
    else
      flash[:name_error] = "Registered Username" if registered_user
      redirect_to get_in_path, notice: 'Incorrect Password'
    end
  end

  def update
    @user = User.find(params[:id])
    @user.update_attributes! params[:user]
    redirect_to tweets_path
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to logout_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:charset => "utf-8"}
    %meta{"http-equiv" => "X-UA-Compatible", :content => "IE=edge,chrome=1"}
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1, maximum-scale=1"}
      %title Cribber
      = stylesheet_link_tag    "application"
      = javascript_include_tag "application"
      = csrf_meta_tags
  %body
    = render 'partials/navigation_bar'
    .container
      = yield

app/views/partials/_navigation_bar.html.haml
.navbar.navbar-fixed-top
  .navbar-inner
    .container-fluid
      %a.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse"}
        %span.icon-circle-arrow-down.icon-white
      = link_to 'Cribber', 'javascript:', class: 'brand'
      - if current_user
        .btn-group.pull-right
          %a.btn.dropdown-toggle{'data-toggle' => 'dropdown', href: '#'}
            = current_user.name
            %span{class: :caret}
          %ul{class: 'dropdown-menu'}
            %li
              = link_to 'logout', logout_path, title: :logout
            %li{class: 'divider'}
            %li
              = link_to 'purge images', purge_images_path
            %li{class: 'divider'}
            %li
              = link_to 'purge tweets', destroy_all_tweets_path
      .nav-collapse.collapse
        %ul.nav.nav-pills
          - if current_user.try(:is_admin)
            %li.active
              = link_to 'Admin Tweet Credentials', admin_credentials_path
          - elsif current_user
            %li{class: ("active" if params[:action] == 'tweets')}
              = link_to 'Tweets', tweets_path
            %li{class: ("active" if ['new', 'edit'].include? params[:action])}
              = link_to 'Edit Account', edit_user_path(current_user)
            - if current_user.tweeter.token?
              %li
                = link_to 'Change Tweet account', twitter_credentials_path
                

app/views/tweeters/admin_credentials.html.haml
.row-fluid
  .span12.blank_block
.row-fluid
  .span2
  .span10
    .span2
    .span6
      = form_for @tweeter, url: save_admin_credentials_path, html: {class: 'well form-vertical'} do |f|
        .fieldset
          .row-fluid
            .span4
              = f.hidden_field :user_id
              .field
                = f.label 'Consumer Key'
                = f.text_field :consumer_key
              .field
                = f.label 'Consumer Secret'
                = f.text_field :consumer_secret
              .actions
                = f.submit 'Save and Logout', class: 'btn-info'

app/views/tweets/tweets.html.haml
.hero-unit.hero_panel
  = form_tag post_tweet_path do
    = text_area_tag :send_tweet, nil, placeholder: 'publish tweet'
    = button_tag content_tag(:div, ( content_tag(:i, nil, class: 'icon-fire') + content_tag(:b, 140) ), id: 'post_tweet'), class: 'btn-large btn-primary'
.row-fluid
  .span12
    - ( tweets = current_user.tweets.order("created_at DESC") ).each_index do |i|
      - next if i.odd?
      .row-fluid
        - tweets[i..(i+1)].each do |tweet|
          .span6.cribber_block
            .row-fluid
              .span1
                - image_url = Image.find_by_twitter_id(tweet.twitter_id).tweet_img(:tiny)
                - if File.readable?(Rails.public_path + image_url.gsub(/\?\d+/, ''))
                  = image_tag image_url
                - else
                  = image_tag 'default_image.png'
              .span11
                .row-fluid
                  %b
                    = tweet.user_name
                  %span{class: :grey_text}
                    = tweet.user_screen_name
                  - if tweet.is_retweeted?
                    %span{class: :grey_text}
                      %i{class: 'icon-chevron-left'}
                      = tweet.retweeter_screen_name
                  %span.fl_right.tweet_actions
                    %i{class: 'icon-download-alt open_links', title: 'Open all links'}
                    - if false
                      = link_to content_tag(:i, '', class: 'icon-trash'), delete_tweet_path(tweet), remote: :true, confirm: "Delete this post?", method: :delete
                    = link_to content_tag(:i, '', class: 'icon-retweet'), retweet_path(tweet.tweet_id), remote: :true, confirm: "Retweet this post?", title: 'retweet'
                .row-fluid
                  .cribber_text
                    = tweet.text

app/views/users/_form.html.haml
.row-fluid
  .span12.blank_block
.row-fluid
  .span2
  .span10
    .span2
    .span6
      = form_for @user, html: {class: 'well user_form form-vertical'} do |f|
        .fieldset
          .row-fluid
            .span4
              .control_group
                = f.label 'Username', class: 'control-label'
                .controls
                  = f.text_field :name
              .error_msg
                = flash[:name_error]
              .control_group
                = f.label :password, class: 'control-label'
                .controls
                  = f.password_field :password
              .error_msg
                = flash[:notice]
              .actions
                = f.submit 'Get In', class: 'btn btn-primary'
            .span2
              %i.icon-user

app/views/users/edit.html.haml
= render 'form'

app/views/users/index.html.haml
%h1 Listing users

%table
  %tr
    %th Name
    %th Crypted password
    %th Email
    %th
    %th
    %th

  - @users.each do |user|
    %tr
      %td= user.name
      %td= user.crypted_password
      %td= user.email
      %td= link_to 'Show', user
      %td= link_to 'Edit', edit_user_path(user)
      %td= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New User', new_user_path

app/views/users/new.html.haml
= render 'form'